# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18bb4dbf3fc7c9532c8d985b7e62c302457f29ffdd467311c024160373906c116ecbbbca2cf99165c5b7c5b0c99e0303958c7516395508c86c3067fd5f8ca0dd

test:
  secret_key_base: b80f3ea0b2d7daf6642fd215b0bf80d2901ff629d887f7cbbbb3b629d83a9e6be85f92518bc7b7284a144f50e8f1a5ed884e1401754e11028e8751d8abd6fef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
